name: cameractrls
base: core22
summary: Camera controls for Linux 
description: |
      A CLI and GUI (GTK, TK) and camera viewer (SDL) to set the camera controls
      in Linux. It can set the V4L2 controls and it is extendable with the non
      standard controls. Currently it has a Logitech extension (Led mode, led
      frequency, BRIO FoV), Kiyo Pro extension (HDR, HDR mode, FoV, AF mode,
      Save), Systemd extension (Save and restore controls with Systemd
      path+service).
      This snap is unofficial and is not endorsed by the upsteam project.  
adopt-info: cameractrls
grade: stable 
confinement: strict

architectures:
  - build-on: amd64

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: hu.irl.cameractrls

apps:
  cameractrls:
    command: usr/bin/cameractrls.py
    plugs:
      - camera
      - home
  cameractrlsgtk:
    extensions: [gnome]
    command: usr/bin/cameractrlsgtk.py
    plugs:
      - camera
      - home
    slots:
      - dbus-daemon
    common-id: hu.irl.cameractrls

parts:
  cameractrls:
    plugin: python
    source-type: git
    source: https://github.com/soyersoyer/cameractrls
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"
    stage-packages:
       - python3-usb
       - libusb-1.0-0
       - libturbojpeg
       - libsdl2-2.0-0
    override-build: |
      snapcraftctl build
      install -Dm755 "cameractrls.py" "cameractrlsgtk.py" "cameraview.py" -t "$SNAPCRAFT_PART_INSTALL/usr/bin"
      install -Dm644 "images/icon_256.png" -t "$SNAPCRAFT_PART_INSTALL/usr/bin/images/"
      install -Dm644 "pkg/hu.irl.cameractrls.metainfo.xml" -t "$SNAPCRAFT_PART_INSTALL/usr/share/metainfo/"
      install -Dm644 "cameractrls.desktop" -t "$SNAPCRAFT_PART_INSTALL/usr/share/applications/"
